### ISSUE TITLE
Instructions for Configuring Pod Security Admission (PSA) 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke1-docs#21]
In the coming v1.4.4, RKE will support configuring Pod Security Admission (PSA)  on clusters version 1.23 and above. 
We need to update the documentation to add instruction for how to use it. 

Related issues:
-  https://github.com/rancher/rke/issues/3034
- https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
# Configure Pod Security Admission in RKE  

**Availability: since RKE v1.4.4**

The Pod Security Admission controller is enabled by default in Kubernetes clusters v1.23 and above. To configure its default behavior, you must provide an admission configuration file and set it to kube-apiserver when provisioning the cluster.

RKE provides three methods for configuring the Pod Security Admission controller. 


## Method 1: use RKE `pod_security_configuration` option  

To use the built-in PSA configuration, you can set the field `services.kube-api.pod_security_configuration` in the cluster.yml file.  

```
services:
  kube-api:
    pod_security_configuration: # restricted or privileged
```


Below is the PodSecurityConfiguration section in the applied admission configuration file when setting `pod_security_configuration` to `privileged`:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      enforce: privileged
      enforce-version: latest
    exemptions: {}
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```

Below is the PodSecurityConfiguration section in the applied admission configuration file when setting `pod_security_configuration` to `restricted`:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```

## Method 2:  use `admission_configuration` to pass customized admission configuration file 

You can directly pass your customized admission configuration file in the cluster.yml by setting the `services.kube-api.admission_configuration` field. 
 
Note:  [`pod-security.admission.config.k8s.io/v1`](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/) configuration requires v1.25+. For v1.23 and v1.24, use [v1beta1](https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/).  
```
services:
  kube-api:
    admission_configuration:
      apiVersion: apiserver.config.k8s.io/v1
      kind: AdmissionConfiguration
      plugins:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1
            kind: PodSecurityConfiguration
            defaults:
              enforce: "restricted"
              enforce-version: "latest"
            exemptions:
              namespaces: ["cattle-system", "cattle-monitoring", "kube-system"]
              runtimeClasses: []
              usernames: []
```



## Method 3:  use `extra_args` to pass customized admission configuration file 

If you want to use an external admission configuration file in the control plane node, you can use the `services.kube-api.extra_args` option to set the path to the in the kube-apiserver.

Note:  [`pod-security.admission.config.k8s.io/v1`](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/) configuration requires v1.25+. For v1.23 and v1.24, use [v1beta1](https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/).  

```
services:
  kube-api:
    extra_args:
      admission-control-config-file: # path to the file
```
