### ISSUE TITLE
AWS Cloud Provider documentation has incorrect code snippet

### ISSUE THREAD

**Issue by markusewalker** [rancher/rke1-docs#78]
### Issue Description
When reviewing over the AWS Cloud Provider [documentation](https://rke.docs.rancher.com/config-options/cloud-providers/aws#using-the-out-of-tree-aws-cloud-provider-for-rke), there is the following code snippet:

```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: external-aws
    useInstanceMetadataHostname: true/false
```
This is accurate for provisioning an RKE1 downstream cluster through Rancher. However, this is the standalone RKE1 documentation and this is misleading to users attempting to configure AWS Cloud Provider. The code snippet should reflect as the following:

```
cloud_provider:
  name: external-aws
  use_instance_metadata_hostname: true/false
```
